### PR TITLE
fixed out of scope error

### PR DESCRIPTION
**Pull request by vchepkov**
previosly to this commit catalog would through an error:
Could not look up qualified variable 'mcollective::facts::enable'; class mcollective::facts has not been evaluated

### CODE REVIEW

**Comment by jorhett** [comment]
That actually forces everyone to get the facts via crontab, which is not the desired intent.

The user has the option of including mcollective::facts or not at their discretion. I just retested without including facts and it performed properly. What error are you seeing?

```
$ sudo puppet agent --test
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for geode.netconsonance.com
Info: Applying configuration version '1448218996'
Notice: /Stage[main]/Mcollective::Facts::Cronjob/Cron[mcollective-facts]/ensure: removed
Notice: Finished catalog run in 8.55 seconds
```

**Comment by vchepkov** [comment]
I don't think it does, since this class actually only defines $enable variable,
but since mcollective::server includes it unconditionally

```
# Ensure the facts cronjob is set up or removed
  include mcollective::facts::cronjob
```
it has to be included, otherwise catalog including mcollective::server fails
This is how I found it

**Comment by jorhett** [comment]
If you read up you'll see the effect of removing the mcollective::facts class. I can provide you output with both Puppet 3 and Puppet 4 both with and without loading the mcollective::facts class.

Originally the facts class did the work. However, in making improvements and fixing problems with $stringify_facts it got refactored but I didn't want to break anyone so it works as it originally did -- if you include the `facts` class, you get the output of facter and puppet facts in the facts file.

So this manifest checks to see if enable is defined (e.g. did you load the facts class?) and does the right thing based on whether that variable is defined.

If you are seeing an error, then please provide the puppet version and full debug output.

**Comment by vchepkov** [comment]
k, I understand
The class still needs to be fixed though, I'll take a look

example doesn't match the definition, there's no enabled attribute in the class and the name of the class is wrong.

```
# mcollective::facts::crontab {
#    $enabled => 'true',
# }
#
class mcollective::facts::cronjob(
  $run_every = 'unknown',
) {
```

I have puppet version 3.8.4

here is code (san hiera)

```
include mcollective
include mcollective::server
include mcollective::middleware
include mcollective::client
mcollective::plugin::agent { ['filemgr','puppet','nettest','package','service']: }
mcollective::plugin::client { ['filemgr','puppet','nettest','package','service']: }
```

and here is the warning:

```
Warning: Scope(Class[Mcollective::Facts::Cronjob]): Could not look up qualified variable 'mcollective::facts::enable'; class mcollective::facts has not been evaluated
```

**Comment by jorhett** [comment]
Yeah when reviewing the code I submitted a doc fix about 20 minutes ago ;)

**Comment by jorhett** [comment]
Please send at least the verbose output showing that it fails to work.

**Comment by jorhett** [comment]
Ahh... found it.  You didn't tell me you were using "puppet apply" which is unfortunately not the same as "puppet agent" in Puppet 3. You should really upgrade to Puppet 4 where they are much more the same beast ;)

```
$ cat test.pp
include mcollective
#include mcollective::facts
include mcollective::server
include mcollective::middleware                                                                                                                                                                                                                           
include mcollective::client

$ sudo puppet apply test.pp
Warning: Scope(Class[Mcollective::Facts::Cronjob]): Could not look up qualified variable 'mcollective::facts::enable'; class mcollective::facts has not been evaluated
Warning: Scope(Class[Mcollective::Server]): Could not look up qualified variable 'puppet::client::package_name'; class puppet::client has not been evaluated
Warning: Scope(Class[Mcollective::Server]): Could not look up qualified variable 'puppet::client::service_name'; class puppet::client has not been evaluated
Notice: Compiled catalog for geode.netconsonance.com in environment production in 2.05 seconds
Error: Parameter require failed on Package[mcollective-puppet-agent]: No title provided and "Package[]" is not a valid resource reference at /etc/puppet/modules/mcollective/manifests/plugin/agent.pp:33
```

**Comment by vchepkov** [comment]
It does work as expected, now that I know what was expected, but it does generate a warning, which is bit untidy

**Comment by vchepkov** [comment]
ha, well, your book is recommending puppetlabs yum repo, and that's what they have there

**Comment by jorhett** [comment]
So I'm sending a fix now which solves the warning, and works in Puppet 4 too :)

My book came out before the Puppet Collections were created. You get modern versions of Puppet from them https://puppetlabs.com/blog/welcome-puppet-collections. "yum install puppet-agent" to get version 4.0 and above.

Thanks for bringing this back to my attention. I had forgotten it was broken.

**Comment by vchepkov** [comment]
Eager to see it. Because it's definitely broken now even in puppet 3, since it depends on the parsing order. 

Try to apply

include mcollective::server
include mcollective::facts

in that order - cron job will be absent

**Comment by vchepkov** [comment]
New code fails for me, not sure why yet
```
Error: Duplicate declaration: Class[Mcollective::Facts::Cronjob] is already declared; cannot redeclare at /root/puppet/modules/mcollective/manifests/facts.pp:12 on node centos7.chepkov.lan
Error: Duplicate declaration: Class[Mcollective::Facts::Cronjob] is already declared; cannot redeclare at /root/puppet/modules/mcollective/manifests/facts.pp:12 on node centos7.chepkov.lan
```

and my last name is Chepkov, not Chepkovby :) (CHANGELOG)

Thank you

**Comment by vchepkov** [comment]
On related note, facter --puppet is deprecated in puppet 4
One should use puppet facts --render-as yaml instead

**Comment by vchepkov** [comment]
works properly now

**Comment by jorhett** [comment]
Fixed in 26f40ce6601cb77be6449cf69f29bfcc20a3b9f0 

I had my setup backwards. I revised to have the deprecated facts class inherit from cronjobs and alter it, and now ordering works perfectly fine.

**Comment by jorhett** [comment]
That deprecation decision was reversed, in large part because I and many others pointed out that it make a very common use case impossible.  They may decide on a new path for Puppet 5, but that's a year+ away at least. This is the only working method at this time which meets mcollective's needs.

**Pull request closed without merging**
